### ISSUE TITLE
Digest loop problem

### ISSUE THREAD

**Issue by pingu1m** [thelgevold/ui-router-ngupgrade#1]
Hi, I'm using the app to bootstrap ng1 ng2 at work. However, every single event is firing the digest loop. To make matters worst, when the package angular material is added even the mouse move triggers the digest loop. 

I'm using this to watch the digest loop
```
        $scope.$watch( function () {
            console.log("digested ...", event)
        })
```
In the friends controller.

**Comment by thelgevold** [comment]
Hm.. Yeah I am noticing that a digest is triggered when clicking on the view.
Not sure what is causing that. Wonder if it's a zone thing...

**Comment by pingu1m** [comment]
I refactor my app. It took almost the same amount of time that I spent making ng1 ng2 work together.
